import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SocketProviders from "@/context/SocketProviders";
import ReduxProvider from "@/context/ReduxProvider";
import Navbar from "@/components/nav/navbar";
import dynamic from "next/dynamic";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className + ' overflow-x-hidden'}>
        <ReduxProvider>
          {/* <SocketProviders> */}
            <Navbar />
            {children}
          {/* </SocketProviders> */}
        </ReduxProvider>
        <ToastContainer className={'mt-20'} />
      </body>
    </html>
  );
}
